config/routes.rb
Rails.application.routes.draw do

  resources :blogs
  #get 'login', to: 'blogs#new' 
  #post 'login', to: 'blogs#new'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy' 
  root to: 'blogs#index'
  post "blog_url", to: 'blogs#index' 

  resources :users
  
  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  get 'authorized', to: 'sessions#page_requires_login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes

  attribute :user

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :blogs
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Email invalid"  }
  validates :password_digest, confirmation: true
  validates :password, length: { minimum: 6}
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?
  def current_user     
   User.find_by(id: session[:user_id])  
  end
  

  def logged_in?   
      !current_user.nil?  
  end


  def authorized
    redirect_to '/blogs' unless logged_in?
      end
  end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  #before_action :authorized, only: [:new, :edit, :update, :create, :show, :destroy]
  skip_before_action :authorized, only:[:index]
  # GET /blogs or /blogs.json
  def index
      if params[:user_id]
        begin
        @user=User.find(params[:user_id])
      rescue ActiveRecord::RecordNotFound => e
        @user=nil
   
        end
        @blogs=@user.present? ? @user.blogs : Blog.all
      elsif current_user
      @blogs=current_user.blogs
      else
     @blogs = Blog.all
      end
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = current_user.blogs.new
    
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = current_user.blogs.build(blog_params)
    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to "/blogs/new", notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      format.html { render :new, notice: "The Blog you are trying to find doesn't exist yet." }
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :authorized, only: [:new, :create, :welcome, :login]

    
  def new
 flash.clear()
  end
  def create
      user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
          session[:user_id] = user.id 
          redirect_to '/blogs/new'
      else
          # if email or password incorrect, re-render login page:
          flash.now.notice = "Incorrect email or password, try again."
          render :new
      end

  end
  def welcome
      
  end
  def login
    redirect_to sign_in_path unless logged_in?  
  end
  def destroy
    #byebug
    session[:user_id] = nil
    redirect_to '/blogs'
  end
    
end

app/controllers/users_controller.rb
  
class UsersController < ApplicationController
     skip_before_action :authorized, only: [:new, :create]
   
  def new   
    @user = User.new
  end
  def create
    @user = User.new(email: params[:user][:email], password: params[:user][:password], password_confirmation: params[:user][:password_confirmation])
   
    respond_to do |format|
      if @user.save
        session[:user_id]=@user.id
        format.html { redirect_to '/blogs/new', notice: "User was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
 
<%=form.hidden_field :user_id %>
  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/blogs/_link.html.erb
<% if current_user %>
  Logged in as: <%= current_user.email %><br>
   <%= button_to "Sign Out", logout_path,  method: :delete %>
    <% else  %>
<div>New User? click on   <%= link_to "Sign up", sign_up_path %> </div>
<div> Already a user? click on <%= link_to "Sign in", sign_in_path %> </div> 


<% end %>

app/views/blogs/edit.html.erb
<%= render 'link' %>
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog, :class => "btn btn-primary btn-sm" %>, 

<%= link_to 'Show', @blog , :class => "btn btn-primary btn-sm"%> |
<td><%= link_to 'Back', new_blog_path(@blog), :class => "btn btn-primary btn-sm" %></td>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<%= form_tag('/blogs', method: :get) do %>

 <div class="field">
    <%= label_tag :user_id %>
    <%= select_tag :user_id, options_for_select(User.all.map{|s|[s.email, s.id]},params[:user_id]), {onchange: 'this.form.submit();'}%>
    </div>
      <% end %> 
  

<table>
<thead>
 <% if @blogs.empty? %>
  <div class="alert alert-success" role="alert">
    No blogs have been created yet by the user
  </div>
  <% else %> 
     <tr>
      <th> Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
     
  </thead>
  <% end %>
  <tbody>
  
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= render 'link' %>

app/views/blogs/new.html.erb
<%= render 'link' %>

 <p id="notice"><%= notice %></p>

  <h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
    <% current_user.blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
  
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h1>New Blog</h1>
<%= render 'form', blog: @blog , :class => "btn btn-primary btn-sm"%>


 

app/views/blogs/show.html.erb
<%= render 'link' %>
<p id="notice"><%= notice %></p>
<% if @blog.nil? %>
<%else%> 
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%end%>
<td><%= link_to 'Back', new_blog_path(@blog) %></td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>

  </head>

  <body>
      <div class="container">
        <%= yield %>
      </div>
        
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= form_with model: @user, url: sign_up_path do |f|  %>

    <% if @user.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being created:</h2>
        <ul>
            <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Sign Up" %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome Page</h1>

<%= link_to 'New Blog', new_blog_path %>